name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '3.2'
          - '3.3'
        rubyopt: [""]
        include:
          - ruby-version: '3.3'
            rubyopt: "--enable-frozen-string-literal --debug-frozen-string-literal"

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby-version }}"
          bundler-cache: true
      - run: bundle exec rake RUBYOPT="${{ matrix.rubyopt }}"
